### ISSUE TITLE
thirdpart: Vorwärtszug um 1 Felder ist nicht möglich

### ISSUE THREAD

**Issue by manuel3108** [EasyDevCpp/SoftwareChallange#15]
Fehler:
```
11:54:54.508 [XStreamClient Receive Thread 623 Client] ERROR s.f.plugins.RoundBasedGameInstance - Ungueltiger Zug von 'Team FLS'.
Vorw�rtszug um 1 Felder ist nicht m�glich
sc.shared.InvalidMoveException: Vorw�rtszug um 1 Felder ist nicht m�glich
	at sc.plugin2018.Move.perform(Move.java:197) [na:na]
	at sc.plugin2018.Game.onRoundBasedAction(Game.java:78) [na:na]
	at sc.framework.plugins.RoundBasedGameInstance.onAction(RoundBasedGameInstance.java:72) [software_challenge-sdk.jar:na]
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:473) [softwarechallenge-server.jar:na]
	at sc.server.Lobby.onRequest(Lobby.java:124) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.onObject(Client.java:297) [softwarechallenge-server.jar:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:148) [software_challenge-sdk.jar:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:98) [software_challenge-sdk.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
11:54:54.509 [XStreamClient Receive Thread 623 Client] DEBUG sc.networking.clients.XStreamClient - Client sc.server.network.Client@380dc6e1: Sending sc.protocol.responses.RoomPacket@585efef1 via sc.networking.TcpNetwork@169ecbd2
DataDump:
<room roomId="c59799c1-431a-4547-b885-36cb9da78181">
  <data class="error" message="Ungueltiger Zug von &apos;Team FLS&apos;.&#xa;Vorw�rtszug um 1 Felder ist nicht m�glich">
    <originalRequest class="move">
      <advance order="0" distance="1"/>
    </originalRequest>
  </data>
</room>
11:54:54.509 [XStreamClient Receive Thread 623 Client] WARN  sc.server.network.Client - An error occured: 
sc.api.plugins.exceptions.GameLogicException: Ungueltiger Zug von 'Team FLS'.
Vorw�rtszug um 1 Felder ist nicht m�glich
	at sc.framework.plugins.RoundBasedGameInstance.catchInvalidMove(RoundBasedGameInstance.java:351) [software_challenge-sdk.jar:na]
	at sc.plugin2018.Game.onRoundBasedAction(Game.java:81) [na:na]
	at sc.framework.plugins.RoundBasedGameInstance.onAction(RoundBasedGameInstance.java:72) [software_challenge-sdk.jar:na]
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:473) [softwarechallenge-server.jar:na]
	at sc.server.Lobby.onRequest(Lobby.java:124) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.onObject(Client.java:297) [softwarechallenge-server.jar:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:148) [software_challenge-sdk.jar:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:98) [software_challenge-sdk.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
```

Log & Replay: [#15.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1502996/15.zip)

**Comment by EasyDevCpp** [comment]
Found evidence...
[15.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1593819/15.zip)
