### ISSUE TITLE
secondpart: Es können nicht 10 Karotten aufgenommen werden

### ISSUE THREAD

**Issue by manuel3108** [EasyDevCpp/SoftwareChallange#19]
```
12:34:01.655 [XStreamClient Receive Thread 703 Client] ERROR s.f.plugins.RoundBasedGameInstance - Ungueltiger Zug von 'Team FLS'.
Es k�nnen nicht 10 Karotten aufgenommen werden.
sc.shared.InvalidMoveException: Es k�nnen nicht 10 Karotten aufgenommen werden.
	at sc.plugin2018.Move.perform(Move.java:197) [na:na]
	at sc.plugin2018.Game.onRoundBasedAction(Game.java:78) [na:na]
	at sc.framework.plugins.RoundBasedGameInstance.onAction(RoundBasedGameInstance.java:72) [software_challenge-sdk.jar:na]
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:473) [softwarechallenge-server.jar:na]
	at sc.server.Lobby.onRequest(Lobby.java:124) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.onObject(Client.java:297) [softwarechallenge-server.jar:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:148) [software_challenge-sdk.jar:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:98) [software_challenge-sdk.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
12:34:01.655 [Thread-735] INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
12:34:01.655 [XStreamClient Receive Thread 703 Client] DEBUG sc.networking.clients.XStreamClient - Client sc.server.network.Client@326070b6: Sending sc.protocol.responses.RoomPacket@16b3c7e6 via sc.networking.TcpNetwork@361dd350
DataDump:
<room roomId="c86a0c12-6744-467b-be52-11b1f145ff9d">
  <data class="error" message="Ungueltiger Zug von &apos;Team FLS&apos;.&#xa;Es k�nnen nicht 10 Karotten aufgenommen werden.">
    <originalRequest class="move">
      <exchangeCarrots order="0" value="10"/>
    </originalRequest>
  </data>
</room>
12:34:01.656 [XStreamClient Receive Thread 703 Client] WARN  sc.server.network.Client - An error occured: 
sc.api.plugins.exceptions.GameLogicException: Ungueltiger Zug von 'Team FLS'.
Es k�nnen nicht 10 Karotten aufgenommen werden.
	at sc.framework.plugins.RoundBasedGameInstance.catchInvalidMove(RoundBasedGameInstance.java:351) [software_challenge-sdk.jar:na]
	at sc.plugin2018.Game.onRoundBasedAction(Game.java:81) [na:na]
	at sc.framework.plugins.RoundBasedGameInstance.onAction(RoundBasedGameInstance.java:72) [software_challenge-sdk.jar:na]
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:473) [softwarechallenge-server.jar:na]
	at sc.server.Lobby.onRequest(Lobby.java:124) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.onObject(Client.java:297) [softwarechallenge-server.jar:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:148) [software_challenge-sdk.jar:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:98) [software_challenge-sdk.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
```

Log und Replay: [#19.zip](https://github.com/EasyDevCpp/SoftwareChallenge/files/1503018/19.zip)

**Comment by manuel3108** [comment]
Cannot see an error in SecondPart between line 30 to 33

**Comment by EasyDevCpp** [comment]
Wie soll ich vorgehen? Irgendeine Idee? Oder einfach so lassen?

**Comment by manuel3108** [comment]
Ich würd es erst mal dabei belassen. Wenn der Fehler allerdings noch einmal auftritt, sollten wir nochmal genauer schauen
