### ISSUE TITLE
SecondPart makes no turn

### ISSUE THREAD

**Issue by EasyDevCpp** [EasyDevCpp/SoftwareChallange#5]

**Comment by manuel3108** [comment]
![5](https://user-images.githubusercontent.com/30698007/31265248-2ca4c8c8-aa6e-11e7-9763-6e2df86d4edf.PNG)
In der log ist folgender Fehler: 

sc.api.plugins.exceptions.GameLogicException: Ungueltiger Zug von 'Bot'.
Vorw�rtszug um 1 Felder ist nicht m�glich
	at sc.framework.plugins.RoundBasedGameInstance.catchInvalidMove(RoundBasedGameInstance.java:351) [software_challenge-sdk.jar:na]
	at sc.plugin2018.Game.onRoundBasedAction(Game.java:81) [na:na]
	at sc.framework.plugins.RoundBasedGameInstance.onAction(RoundBasedGameInstance.java:72) [software_challenge-sdk.jar:na]
	at sc.server.gaming.GameRoom.onEvent(GameRoom.java:473) [softwarechallenge-server.jar:na]
	at sc.server.Lobby.onRequest(Lobby.java:124) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.notifyOnPacket(Client.java:116) [softwarechallenge-server.jar:na]
	at sc.server.network.Client.onObject(Client.java:297) [softwarechallenge-server.jar:na]
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:148) [software_challenge-sdk.jar:na]
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:98) [software_challenge-sdk.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]

Ansonsten hat er bis Feld 41 gespielt, d.h. er macht schon was
